name: VillagerUtils
version: ${project.version}
main: io.github.redwallhp.villagerutils.VillagerUtils
description: Tools for managing villagers
author: redwall_hp
contributors: [Mats1300]
website: https://github.com/NerdNu/VillagerUtils
api-version: 1.21.8
softdepend: [WorldGuard]


permissions:
  villagerutils.*:
    description: Gives access to all commands and functions
    children:
      villagerutils.editvillager: true
  villagerutils.editvillager:
    description: Access the /villager command


commands:
  villager:
    description: Villager editing commands
    usage: /villager <subcommand>
  vtrade:
    description: Create and edit a villager trade
    usage: /vtrade <subcommand>